### ISSUE TITLE
Can y'all rollout `067845ea6` to the `install_script.sh`?

### ISSUE THREAD

**Issue by izzyleung** [DataDog/agent-linux-install-script#48]
Hey Datadog team, we have encountered a major issue with using the Datadog agent installation script for Datadog agent version `Agent 7.45.0 - Commit: 964e770 - Serialization version: v5.0.81 - Go version: go1.19.9`.

In short, we use the script `install_script.sh` provided by Datadog to install the agent. (Yes, we are aware that the script is considered out-dated), below is how we invoke the script:
```DD_AGENT_MAJOR_VERSION=7 DD_API_KEY=$api_key DD_HOST_TAGS=$host_tags DD_SITE="datadoghq.com" bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script.sh)"```

What we noticed is that with the latest version of Datadog agent, the config file has a new section added which has a `tag` field in it, and it seems like the installation script will try to add our tags to the field `snmp_listener.configs.tags`, which will cause the Datadog agent to quit immediately and cannot start.

When we run the debug command `/opt/datadog-agent/bin/agent/agent check`, here is the output:
```Error: unable to load Datadog config file: While parsing config: yaml: line 962: did not find expected key```

Below are the structure of the new config file, it seems like the new field confused the agent binary
```
# ...
# snmp_listener:
  ## @param configs - list - required
  # ...
  # configs:
    # tags:
    #   - <KEY_1>:<VALUE_1>
    #   - <KEY_2>:<VALUE_2>
```

What we noticed is that y'all addressed this in release https://github.com/DataDog/agent-linux-install-script/releases/tag/1.17.1 but was wondering if it's possible for y'all to also roll [this change](https://github.com/DataDog/agent-linux-install-script/commit/067845ea659e77903cd5648b882d315cd13b36f1) to the old installation script, thank in advance. 🙏

**Comment by chouetz** [comment]
Hello @izzyleung, would it be possible to know which constraint(s) prevent(s) you from upgrading to the `install_script_agent7.sh`. We would certainly favour an upgrade to the latest version than a modification on an outdated script, even if the modification complexity is minor. 
Many thanks in advance and sorry for inconvenience
